lang: fr
title: Yohann Le Guennec
description: Enseignement, recherche et publications en génie des procédés.
url: "https://yohannleguennec-univlorraine.github.io"
baseurl: "/CV-YLG"
timezone: Europe/Paris
future: false

defaults:
  - scope:
      path: "blog/posts"
    values:
      layout: post
      author: Yohann Le Guennec
